//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiToDo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarefas1
    {
        public tarefas1()
        {
            this.comentarios1 = new HashSet<comentarios1>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string concluido { get; set; }
    
        public virtual ICollection<comentarios1> comentarios1 { get; set; }
    }
}
